### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object error

### ISSUE THREAD

**Issue by brainie** [vaseline555/Federated-Learning-in-PyTorch#2]
Good evening sir.

please I come across this error

`"RecursionError: maximum recursion depth exceeded while calling a Python object"`

whenever i run main.py even after installing all the dependencies
please is there anything I can do to make the code work?

**Comment by vaseline555** [comment]
Dear @brainie 
Hi, could you please clarify what line does the error occur, please?

Thank you.

p.s.) I will update the whole repo. (i.e., ver 2.0 of this implementation) as soon.

**Comment by brainie** [comment]
Good afternoon

the error started from line 32

```
  Traceback (most recent call last):
  File "D:\Johnson Ibironke\Documents\Masters Programme\Git_Repos\Federated_learning\Federated-Averaging-PyTorch-main\Federated-Averaging-PyTorch-main\main.py", line 32, in <module>
```

Here is the error in full

```
Traceback (most recent call last):
  File "D:\Johnson Ibironke\Documents\Masters Programme\Git_Repos\Federated_learning\Federated-Averaging-PyTorch-main\Federated-Averaging-PyTorch-main\main.py", line 32, in <module>
    writer = SummaryWriter(log_dir=log_config["log_path"], filename_suffix="FL")
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\site-packages\torch\utils\tensorboard\writer.py", line 220, in __init__
    self._get_file_writer()
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\site-packages\torch\utils\tensorboard\writer.py", line 250, in _get_file_writer
    self.file_writer = FileWriter(self.log_dir, self.max_queue,
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\site-packages\torch\utils\tensorboard\writer.py", line 60, in __init__
    self.event_writer = EventFileWriter(
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\site-packages\tensorboard\summary\writer\event_file_writer.py", line 72, in __init__
    tf.io.gfile.makedirs(logdir)
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 900, in makedirs
    return get_filesystem(path).makedirs(path)
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\site-packages\tensorboard\compat\tensorflow_stub\io\gfile.py", line 201, in makedirs
    os.makedirs(path, exist_ok=True)
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\os.py", line 225, in makedirs
    makedirs(name, mode)
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\os.py", line 225, in makedirs
    makedirs(name, mode)
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\os.py", line 225, in makedirs
    makedirs(name, mode)
  [Previous line repeated 984 more times]
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\os.py", line 210, in makedirs
    head, tail = path.split(name)
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\ntpath.py", line 186, in split
    seps = _get_bothseps(p)
  File "C:\Users\Johnson Ibironke\.conda\envs\FEDAVG\lib\ntpath.py", line 35, in _get_bothseps
    if isinstance(path, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

Please I would greatly appreciate it, if you can put me through implementing the code set by step, especially with the use of the dataset.

**Comment by vaseline555** [comment]
Sorry for super late reply. I think you might give a wrong path to the configuration file. Please kindly check your config.yaml file.
